# Generated by Django 5.0.4 on 2024-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=255)),
                ("hotel_location", models.CharField(max_length=255)),
                ("reviews_in_stars", models.IntegerField(blank=True, null=True)),
                ("total_rooms", models.IntegerField(blank=True, null=True)),
                ("available_rooms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hotel",
            },
        ),
    ]
